title: GitHub Blog
author: Sean Kelly

description: > # this means to ignore newlines until "baseurl:"
  I am currently finding my way around GitHub and GitHub Pages.
# social links
twitter_username: sdklly
github_username:  sdklly

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
